apiVersion: bench.example.com/v1alpha1
kind: Bench
metadata:
  name: example-bench
spec:
  # cleanup: true
  uperf:
    # To disable uperf, set pairs to 0
    pair: 0
    proto: tcp
    test_type: stream
    nthr: 2
    size: 16384
    runtime: 10
  fio:
    # To disable fio, set clients to 0
    job: seq_write # either of seq_write, seq_read, seq_rw, rand_write, rand_read, rand_rw
    clients: 1
    jobname: seq-write
    bs: 4k
    iodepth: 4
    runtime: 60
    numjobs: 1
    filesize: 1
    storageclass: rook-ceph-block
    storagesize: 27Gi
  sysbench:
    enabled: true
    tests:
    - name: cpu
      parameters:
        cpu-max-prime: 2000
    - name: fileio
      parameters:
        file-test-mode: rndrw
