---
- name: Generate fio test
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: fio-test-shekhar
        namespace: '{{ meta.namespace }}'
      data:
        fiojob: "{{ lookup('template', 'job.fio.{{fio.job}}') }}"
  when: fio.clients > 0

- name: Create PVC(s)
  k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: "claim1"
        namespace: '{{ meta.namespace }}'
        annotations:
           volume.beta.kubernetes.io/storage-class: "{{fio.storageclass}}"
      spec:
         accessModes:
           - ReadWriteOnce
         resources:
           requests:
             storage: "{{fio.storagesize}}"

- name: Start Server(s)
  k8s:
    definition:
      kind: Pod
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-fio-client-{{item}}-bench'
        namespace: '{{ meta.namespace }}'
        labels:
          app: fio-bench-server
      spec:
        containers:
        - name: bench-server
          image: "quay.io/jtaleric/fio:testing"
          command: ["/bin/sh","-c"]
          args:
           - "cat /tmp/fio/fiojob;
              fio /tmp/fio/fiojob"
          volumeMounts:
          - name: config-volume
            mountPath: "/tmp/fio"
        volumes:
        - name: config-volume
          persistentVolumeClaim: 
            claimName: claim1
          configMap:
            name: fio-test-shekhar
        restartPolicy: Never
  when: fio.clients > 0
  with_sequence: start=1 count={{fio.clients}}
